language: java
notifications:
  slack:
    secure: AdUBqh22PIBnl0M32J8n/CToG4AKNw2QbSk5i0bUBEI9pDgh1lYp4un4Ua5Iofc4+OJ+890epizm1LQY/t/MijU0DBDqGLbgpQcEupQv8zCHJyFNI0TgOICUBAEfsIaRtamWYhwJeb/0f71ch9IWGo4F88Fizz1SCTgvpYlryO4=
deploy:
  provider: releases
  api_key:
    secure: h5c8GCMj2t1mtiGnJjAKzVDN9Avx6ryifKYVgp64piENM+QEcIu6UrUysbJLmdQp5+LEqzD1VgfDYyVsYIHY7EVt4VSQ/JxKDR0hTS3SD8cEh6wrOayBuFtyY0DE2qyr/jkW+qWMhg4+vX9QLR6NTVLNmCT1Uh29TQdg8E3QepE=
  file: build/distributions/xld-mongodb-plugin-1.0.1.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-mongodb-plugin
